services:
  - type: web
    name: crediScope-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn crediScope_ai.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crediScope_ai.settings
      - key: SECRET_KEY
        value: your-django-secret-key
      - key: DEBUG
        value: False
