services:
  - type: web
    name: crediscope-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn crediScope_ai.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: yourdomain.onrender.com
