services:
  - type: web
    name: crediscope-ai
    env: python
    buildCommand: ""
    startCommand: gunicorn crediscope_ai.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crediscope_ai.settings
